resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/SaurabhQA/flight-school
    branch: master
- name: runOnConcourse
  type: git
  source:
    uri: https://github.com/SaurabhQA/runOnConcourse
    branch: master
jobs:
- name: job-A 
  serial_groups: [serial-group-1]
  plan:
  - get: flight-school
    trigger: true
  - task: tests
    file: flight-school/buildTest.yml
- name: job-B 
  serial_groups: [serial-group-2]
  plan:
  - get: runOnConcourse
  - get: flight-school
    trigger: true
  - task: tests
    file: flight-school/buildTest.yml

- name: job-C 
  serial_groups: [serial-group-1,serial-group-2]
  plan:
  - get: flight-school
    passed: 
    - job-A
    - job-B
    trigger: true
  - task: sleep
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      run:
        path: sleep
        args: ["20"]
- name: job-D 
  serial_groups: [serial-group-1,serial-group-2,]
  plan:
  - get: flight-school
    trigger: true
    passed: [job-C]
  - task: sleep
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      run:
        path: sleep
        args: ["60"]
